Doc saver
googleapis/langchain-google-cloud-sql-mysql-python pull request #14
Opened 2024-01-31 00:41 UTC by loeng2023

Add document saver class and support save/load/delete user journeys.

In detail:
- Load documents via default table
- Load documents via custom table/metadata
- Load documents via custom page content columns
- Load documents via custom metadata columns
- Initialize MySQLDocumentSaver with existing table
- Initialize custom MySQLDocumentSaver table & add documents with metadata
- Delete documents

2024-01-31 14:30 UTC, jackwotherspoon requested changes
First quick pass, overall looks great 👏

2024-01-31 14:30 UTC, jackwotherspoon commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +        stmt = sqlalchemy.text("")
do we need this line?

2024-01-31 14:30 UTC, jackwotherspoon commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +            raise ValueError("One of table_name or query needs be specified.")
empty strings are falsy values in Python so lets use the `not` here for a more Pythonic approach
```suggestion
        if not self.table_name and not self.query:
            raise ValueError("One of 'table_name' or 'query' must be specified.")
```

2024-01-31 14:30 UTC, jackwotherspoon commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +            raise ValueError("Cannot specify both table_name and query.")
Let's make this error actionable for the end user...
```suggestion
            raise ValueError("Cannot specify both 'table_name' and 'query'. Specify 'table_name' to load entire table or 'query' to load a specific query.")
```

2024-01-31 14:34 UTC, jackwotherspoon commented
Added `do not merge` label for now since this PR is quite large. Let's wait for the `MySQLChatMessageHistory` PR to get merged into main first before merging this into our staging branch.

2024-01-31 19:47 UTC, loeng2023 commented on src/langchain_google_cloud_sql_mysql/mysql_engine.py
> +        return metadata.tables[table_name]
If we add it as a method of docsaver, then we need refer engine as `self.engine.engine`. Since load table is generic function that is not specific to doc saver/loader, I feel it make sense to put it at engine wrapper layer.

If we don't want customer to use it, I can rename it to `_load_document_table`.

2024-01-31 19:50 UTC, loeng2023 commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +        stmt = sqlalchemy.text("")
To pass mypy check. If we have `stmt = None` here, mypy complains that `connection.execute(stmt)` doesn't support Optional.

2024-01-31 21:29 UTC, loeng2023 commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +            raise ValueError("One of table_name or query needs be specified.")
Thanks for suggestion. Updated.

2024-01-31 21:29 UTC, loeng2023 commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +            raise ValueError("Cannot specify both table_name and query.")
Updated.

2024-01-31 21:53 UTC, jackwotherspoon commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +        stmt = sqlalchemy.text("")
@loeng2023 
what if we just remove this line and make the below as follows:
```python
if self.query:
    stmt = sqlalchemy.text(self.query)
else:
    stmt = sqlalchemy.text(f"select * from `{self.table_name}`;")
```

Since you have already validated that one or the other is set you can just use the logic, if query is not set use table_name...

2024-01-31 21:53 UTC, jackwotherspoon commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +        stmt = sqlalchemy.text("")
I think mypy would no longer throw an issue...

2024-01-31 21:56 UTC, loeng2023 commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +        stmt = sqlalchemy.text("")
Sure, updated.

2024-02-02 00:17 UTC, loeng2023 commented on src/langchain_google_cloud_sql_mysql/mysql_engine.py
> +        return metadata.tables[table_name]
I renamed it to _load_document_table

2024-02-02 00:17 UTC, loeng2023 commented
@jackwotherspoon @totoleon Added unit tests and confirmed text spilter is no-op. Code is ready for review.

2024-02-02 20:40 UTC, totoleon approved these changes
Overall LGTM with the comments resolved.

2024-02-02 20:45 UTC, loeng2023 commented on src/langchain_google_cloud_sql_mysql/mysql_engine.py
> +    def _load_document_table(self, table_name: str) -> sqlalchemy.Table:
It can be used for loading existing table that is not initialized by init_document_table fucntion.

2024-02-02 22:06 UTC, jackwotherspoon commented
Removed `do not merge` label and switched base to main since this is a large enough PR to go right to main

2024-02-02 23:17 UTC, loeng2023 commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +                for column, field_type in zip(column_names, field_types):
Done. Moved them into `column_types`.

2024-02-02 23:17 UTC, loeng2023 commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +        Document page content defaults to the first columns present in the query or table and
Done

2024-02-02 23:18 UTC, loeng2023 commented on src/langchain_google_cloud_sql_mysql/mysql_engine.py
> +            metadata_columns (List[str]): A list of SQLAlchemy Columns to create for custom metadata.
Thanks for capturing this. Fixed.

2024-02-02 23:18 UTC, loeng2023 commented on src/langchain_google_cloud_sql_mysql/mysql_engine.py
> +                in “metadata” field list (Default: True).
Thanks for catching it! Fixed.

2024-02-02 23:18 UTC, loeng2023 commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +        self._table = self.engine._load_document_table(self.table_name)
Done.

2024-02-02 23:33 UTC, loeng2023 commented on tests/unit/test_doc2row.py
> +    }
This only works for default content columns and metadata columns. For majority of test cases here, we have customized metadata column, so that _parse_doc_from_row will lose information and therefore cannot recover original row here.
But for doc-to-row-to-doc coversion, we can ensure the coversion doesn't lose information as long as we use default metadata column to store extra metadata.
Added a test case `test_doc2row2doc_customized_metadata` to test conservation of document under different metadata schema.

2024-02-02 23:39 UTC, loeng2023 commented on tests/integration/test_mysql_loader.py
> +def test_delete_doc_with_default_metadata(engine):
Make sense. Updated test to delete twice
```
    saver.delete(docs[:1])
    assert len(loader.load()) == 1

    saver.delete(docs)
    assert len(loader.load()) == 0
```

2024-02-06 18:09 UTC, merged