feat: Add document saver class and support save/load/delete user journey
googleapis/langchain-google-cloud-sql-mysql-python pull request #16
Opened 2024-02-06 18:11 UTC by loeng2023

Add document saver class and support save/load/delete user journeys.

In detail:

- Load documents via default table
- Load documents via custom table/metadata
- Load documents via custom page content columns
- Load documents via custom metadata columns
- Initialize MySQLDocumentSaver with existing table
- Initialize custom MySQLDocumentSaver table & add documents with metadata
- Delete documents

2024-02-06 22:33 UTC, averikitsch requested changes, later dismissed

2024-02-06 22:33 UTC, averikitsch commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +        MySQLDocumentSaver allows for saving of langchain documents in dataabase. If the table
```suggestion
        MySQLDocumentSaver allows for saving of langchain documents in a database. If the table
```

2024-02-06 22:33 UTC, averikitsch commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +        cache all documents in memory at once.
```suggestion
        caching all documents in memory at once.
```

2024-02-06 22:33 UTC, averikitsch commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +        self._create_table_if_not_exists()
Kurtis and I have decided that the table initialization should happen outside the Saver, see convo https://github.com/googleapis/langchain-google-cloud-sql-mssql-python/pull/9#discussion_r1478561574.

2024-02-06 22:33 UTC, averikitsch commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +    row: Dict[str, Any] = {"page_content": doc.page_content}
nit: You could use DEFAULT_CONTENT_COLUMN here

2024-02-06 22:39 UTC, loeng2023 commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +        self._create_table_if_not_exists()
In that case, instead of create table here. We only check if the table contains "page_content" column. If it doesn't, we raise an error?

2024-02-07 01:35 UTC, loeng2023 commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +        self._create_table_if_not_exists()
Removed _create_table_if_not_exists and made it raise error if 'page_content' is not a column of specified table. Also updated integration tests.

2024-02-07 01:35 UTC, loeng2023 commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +    row: Dict[str, Any] = {"page_content": doc.page_content}
Sure. Updated

2024-02-07 01:35 UTC, loeng2023 commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +        MySQLDocumentSaver allows for saving of langchain documents in dataabase. If the table
Done.

2024-02-07 01:35 UTC, loeng2023 commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +        cache all documents in memory at once.
Done.

2024-02-07 16:06 UTC, jackwotherspoon commented on src/langchain_google_cloud_sql_mysql/mysql_engine.py
> +        metadata.create_all(self.engine)
@loeng2023 probably better to use `create` instead of `create_all` here since we are only creating a single table.

Ref: https://docs.sqlalchemy.org/en/20/core/metadata.html#creating-and-dropping-database-tables
```suggestion
        doc = sqlalchemy.Table(table_name, metadata, *columns)
        doc.create(self.engine)
```

2024-02-07 18:19 UTC, loeng2023 commented on src/langchain_google_cloud_sql_mysql/mysql_engine.py
> +        metadata.create_all(self.engine)
Thanks for suggestion. Updated to use `create`.

2024-02-08 20:42 UTC, kurtisvg requested changes

2024-02-08 20:42 UTC, kurtisvg commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +            ]
Can we put a more illustrative comment on what this means? 

I don't know whats in `result_proxy.cursor.description`, or why we are casting it to a tuple and slicing (I'm assuming it's maybe col_name / col_type but it would be good to clarify what's happening).

2024-02-08 20:42 UTC, kurtisvg commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +                        row_data[column] = value
Why do we handled JSON separately here? Are the rest coming in native types but sqlalchemy presents JSON as a string?

2024-02-08 20:42 UTC, kurtisvg commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +                    value = getattr(row, column)
if `row` is a Dict, why can't we use `value = row[column]`?

2024-02-08 20:42 UTC, kurtisvg commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +    )
@averikitsch is this the right behavior? it looks like content_column is becoming "row1 row2 row3"

2024-02-08 20:42 UTC, kurtisvg commented on tests/unit/test_doc2row.py
> +    )
nit: if we have to use () to spread a line across multiple lines it probably doesn't need to be a single line in the first place. Please update the other tests as well.
```suggestion
    doc = _parse_doc_from_row(
        [DEFAULT_CONTENT_COL], [DEFAULT_METADATA_COL], row_default
    )
    assert doc == test_doc
```

2024-02-08 20:42 UTC, kurtisvg commented on tests/integration/test_mysql_loader.py
> +    engine.init_document_table(table_name)
where are we cleaning these tables up?

2024-02-08 21:43 UTC, loeng2023 commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +                        row_data[column] = value
When we obtain result by directly executing query, 
```
connection.execute(sqlalchemy.text(self.query))
```
the result row's JSON field contains JSON string. We need manually parse them to dictionary.

When we save row via sqlalchemy
```
conn.execute(sqlalchemy.insert(self._table).values(row))
```
it accept dictionary for JSON field.

Implementation wise it's easier to do JSON fields parsing before passing the row to _parse_doc_from_row.

2024-02-08 21:44 UTC, loeng2023 commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +                    value = getattr(row, column)
row object here has type `sqlalchemy.engine.row.Row`

2024-02-08 21:47 UTC, loeng2023 commented on tests/integration/test_mysql_loader.py
> +    engine.init_document_table(table_name)
At line 44, @pytest.fixture(name="engine") got called for every test cases.

2024-02-08 21:51 UTC, loeng2023 commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +            ]
Sure added comment that explains `cursor.description`.

The definition of `cursor.description` can be found here:
https://peps.python.org/pep-0249/#description

We need cast it to tuple here otherwise mypy will complain
```
error: Value of type "DBAPIType" is not indexable
```

2024-02-08 21:51 UTC, loeng2023 commented on tests/unit/test_doc2row.py
> +    )
Sure, updated.

2024-02-09 19:14 UTC, loeng2023 commented
@kurtisvg @averikitsch Code is ready for another round of review now.

2024-02-12 20:30 UTC, kurtisvg approved these changes

2024-02-12 21:10 UTC, merged