docs:  document loader guide books
googleapis/langchain-google-cloud-sql-mysql-python pull request #18
Opened 2024-02-12 21:31 UTC by loeng2023

2024-02-12 21:39 UTC, jackwotherspoon reviewed
quick first pass, havent looked at notebook yet

2024-02-12 21:39 UTC, jackwotherspoon commented on README.md
> +from langchain_google_cloud_sql_pg import MySQLEngine, MySQLLoader
```suggestion
from langchain_google_cloud_sql_mysql import MySQLEngine, MySQLLoader
```

2024-02-12 21:39 UTC, jackwotherspoon commented on README.md
> +## Document Loader Usage
I think we should keep `Usage` as an h2 header and make `Document Loader` an h3 sub-header

2024-02-12 21:39 UTC, jackwotherspoon commented on README.md
> +Use a document loader to load data as LangChain `Document`s.
link to langchain docs for document?

2024-02-12 21:39 UTC, jackwotherspoon commented on README.md
> +engine = MySQLEngine.from_instance("project-id", "region", "my-instance", "my-database")
should we use a format that makes it more straightforward which vars should be replaced (all caps)... `<PROJECT-ID>` etc.

2024-02-12 22:14 UTC, loeng2023 commented on README.md
> +from langchain_google_cloud_sql_pg import MySQLEngine, MySQLLoader
Thanks for capture this. Fixed.

2024-02-14 18:08 UTC, jackwotherspoon requested changes
@loeng2023 A few things on my second pass.

1. I think we want to simplify this notebook and try to remove as many SQLAlchemy engine execution statements as possible. Ideally all `.execute` commands happen internally in our library and users in this notebook only use our APIs.
2. Right now document saver and loader are quite intermingled. We should clean this up so that we follow the outline given by Averi. Basic usage should cover all DocLoader APIs and only show "load via table name" and "load via query". All document saver API ref and examples should be moved to `Advanced Usage`

2024-02-14 18:08 UTC, jackwotherspoon commented on docs/document_loader.ipynb
> +    "Save langchain documents with `MySQLDocumentSaver.add_documents(<documents>)`."
based on Averi's notebook doc `Basic Usage` should only cover the following:
* Setting up connection object, if needed
* Load via table name
* Load via query

Document saver should be in `Advanced Usage`.

2024-02-14 19:48 UTC, loeng2023 commented on docs/document_loader.ipynb
> +    "    conn.commit()\n",
But without drop table command. Users won't be able to run examples by simply clicking run. They will have to manual drop table in order to run next example.

2024-02-14 20:00 UTC, jackwotherspoon commented on docs/document_loader.ipynb
> +    "    conn.commit()\n",
then maybe we should add the `overwrite_existing` arg to drop table if it exists as functionality within our lib...

It seems messy if I have to drop a table manually before I even know what I'm doing. I don't see any of the other doc loader integrations dropping tables prior to starting...

2024-02-15 00:58 UTC, loeng2023 commented on docs/document_loader.ipynb
> +    "Save langchain documents with `MySQLDocumentSaver.add_documents(<documents>)`."
But we cannot load documents without saving them first. Moving saver into basic usage makes the demo experience smoother.

2024-02-15 00:59 UTC, loeng2023 commented on docs/document_loader.ipynb
> +    "engine = MySQLEngine.from_instance(\n",
I copy-pasted part of your doc section here and added a link.

2024-02-15 00:59 UTC, loeng2023 commented on docs/document_loader.ipynb
> +    "import sqlalchemy"
Done.

2024-02-15 00:59 UTC, loeng2023 commented on docs/document_loader.ipynb
> +    "    print(result.fetchall())"
Sure, removed it.

2024-02-15 01:00 UTC, loeng2023 commented on docs/document_loader.ipynb
> +    "    conn.commit()\n",
Make sense, I added `overwrite_existing` to https://github.com/googleapis/langchain-google-cloud-sql-mysql-python/pull/19

2024-02-15 01:00 UTC, loeng2023 commented on docs/document_loader.ipynb
> +    "Login datebase using IAM database authentication: https://cloud.google.com/sql/docs/mysql/iam-logins\n",
Done. I think your doc organize it better. So copy-pasted.

2024-02-15 01:04 UTC, loeng2023 commented on README.md
> +## Document Loader Usage
I think we can keep it in this way the same as https://github.com/googleapis/langchain-google-cloud-sql-pg-python

2024-02-15 01:04 UTC, loeng2023 commented on README.md
> +Use a document loader to load data as LangChain `Document`s.
Sure. Added [document loader](https://python.langchain.com/docs/modules/data_connection/document_loaders/)

2024-02-16 20:56 UTC, kurtisvg approved these changes

2024-02-16 21:39 UTC, jackwotherspoon commented on docs/document_loader.ipynb
> +    "# Google Cloud SQL MySQL\n",
This is the official wording of the product
```suggestion
    "# Google Cloud SQL for MySQL\n",
```

2024-02-16 21:39 UTC, jackwotherspoon commented on docs/document_loader.ipynb
> +    "table_name = \"test-default\"  # @param {type:\"string\"}"
can we match the section headers with those of the chat message history docs. Normally arguments users have to fill in should be fully capitalized. If we follow the pattern in the chat history notebook of setting most of these values right before you use them i think it flows a bit cleaner. We should also stay consistent on variable naming `instance_id` vs `INSTANCE` or `db_name` `vs DATABASE`

2024-02-16 21:39 UTC, jackwotherspoon commented on docs/document_loader.ipynb
> +    "### Library Installation\n",
nit: maybe add the emojis in the headers from chat message history? I find they lighten it up and make the doc seem more beginner friendly.

2024-02-16 21:39 UTC, jackwotherspoon commented on docs/document_loader.ipynb
> +    "%pip install -U -q langchain-google-cloud-sql-mysql"
nit: better to be more verbose so users know what these flags mean
```suggestion
    "%pip install --upgrade --quiet langchain-google-cloud-sql-mysql"
```

2024-02-16 21:39 UTC, jackwotherspoon commented on docs/document_loader.ipynb
> +  {
it looks like we are missing the `Set your Google Cloud Project` section? I think this can lead to undefined behavior if it is ommitted...

2024-02-16 21:39 UTC, jackwotherspoon commented on docs/document_loader.ipynb
> +    "Please refer to [notebook for `MySQLChatMessageHistory`](https://github.com/googleapis/langchain-google-cloud-sql-mysql-python/blob/main/docs/chat_message_history.ipynb#MySQLEngine-Connection-Po
should we just have all the info re-copied here? I think it is better than having users open another page. It pertains to the API spec so i think it is relevant.

2024-02-16 22:02 UTC, loeng2023 commented on docs/document_loader.ipynb
> +    "# Google Cloud SQL MySQL\n",
Done.

2024-02-16 22:02 UTC, loeng2023 commented on docs/document_loader.ipynb
> +    "### Library Installation\n",
Sure

2024-02-16 22:02 UTC, loeng2023 commented on docs/document_loader.ipynb
> +    "table_name = \"test-default\"  # @param {type:\"string\"}"
Sure. Updated

2024-02-16 22:02 UTC, loeng2023 commented on docs/document_loader.ipynb
> +    "%pip install -U -q langchain-google-cloud-sql-mysql"
Done.

2024-02-16 22:04 UTC, loeng2023 commented on docs/document_loader.ipynb
> +  {
I feel getting project_id something too trivial to mention here. But sure we can add it here if you insist.

2024-02-16 22:04 UTC, loeng2023 commented on docs/document_loader.ipynb
> +    "Please refer to [notebook for `MySQLChatMessageHistory`](https://github.com/googleapis/langchain-google-cloud-sql-mysql-python/blob/main/docs/chat_message_history.ipynb#MySQLEngine-Connection-Po
Sure, I copied your entire section now.

2024-02-16 22:15 UTC, jackwotherspoon commented on docs/document_loader.ipynb
> +    "\n",
we don't need PROJECT_ID here since we set it below.

2024-02-16 22:16 UTC, jackwotherspoon commented on docs/document_loader.ipynb
> +    "Before saving or loading documents from MySQL table, we need first configures a connection pool to Cloud SQL database. The `MySQLEngine` configures a [SQLAlchemy connection pool](https://docs.sq
Kurtis got me to remove mention of SQLAlchemy in case we update the underlying connection pool in the future
```suggestion
    "Before saving or loading documents from MySQL table, we need first configures a connection pool to Cloud SQL database. The `MySQLEngine` configures a  connection pool to your Cloud SQL database, enabling successful connections from your application and following industry best practices.\n",
```

2024-02-16 22:17 UTC, jackwotherspoon approved these changes
LGTM, two small nits in my previous comment

2024-02-16 22:21 UTC, loeng2023 commented on docs/document_loader.ipynb
> +    "\n",
Done.

2024-02-16 22:21 UTC, loeng2023 commented on docs/document_loader.ipynb
> +    "Before saving or loading documents from MySQL table, we need first configures a connection pool to Cloud SQL database. The `MySQLEngine` configures a [SQLAlchemy connection pool](https://docs.sq
Done.

2024-02-16 22:34 UTC, merged