feat: support saving with customized content column and saving/loading with non-default metadata JSON column.
googleapis/langchain-google-cloud-sql-mysql-python pull request #19
Opened 2024-02-13 00:40 UTC by loeng2023

Summary of changes:
- MySQLEngine
  - init_document_table can create column with non-default name `content_column` and `metadata_json_column`, deprecate `store_metadata`.
- MySQLLoader
  - Add `metadata_json_column` for loading document.metadata from non-default JSON metadata field. 
- MySQLSaver
  - Add `content_column` for saving document.page_content into non-default content field.
  - Add `metadata_json_column` for saving document.metadata into non-default JSON metadata field.
  - Support deleting document with non-default content and JSON metadata field.
- test_mysql_loader.py
  - test_save_doc_with_customized_metadata will use non-default content and JSON metadata column.
  - test_delete_doc_with_default_metadata will use non-default content and JSON metadata column.

2024-02-13 19:19 UTC, kurtisvg requested changes

2024-02-13 19:19 UTC, kurtisvg commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +            Default: `langchain_metadata`. Optional.
I think the behavior we want is "when 'metadata_json_column' = None, use langchain_metadata _if it exists_". 

If they explicitly mention a col name and it doesn't exist, that's an error.

2024-02-13 19:32 UTC, loeng2023 commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +            Default: `langchain_metadata`. Optional.
Yes, it is default to None. We set it to langchain_metadata if None, and if it doesn't exists, it will be ignored.

Currently error only raise for names specified in `metadata_columns`, if they don't exists in query result.

How about a scenario that
```
`metadata_columns` = ["a", "b"]
`metadata_json_column` = "c"
```
user specify metadata_json_column but didn't include it in `metadata_columns` ?

should we raise error if "c" doesn't exists in query result?

2024-02-13 22:17 UTC, kurtisvg commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +            Default: `langchain_metadata`. Optional.
Yes

2024-02-14 19:35 UTC, loeng2023 commented on src/langchain_google_cloud_sql_mysql/mysql_loader.py
> +            Default: `langchain_metadata`. Optional.
Also updated int test test_load_from_query_with_langchain_metadata to reflect this change.

2024-02-15 22:45 UTC, kurtisvg approved these changes

2024-02-15 22:51 UTC, merged