feat: add MySQLVectorStore initialization methods
googleapis/langchain-google-cloud-sql-mysql-python pull request #52
Opened 2024-03-25 11:35 UTC by jackwotherspoon

Adding `MySQLVectorStore` and all the different class methods to initialize it.

Still need to add tests.

2024-03-25 15:33 UTC, jackwotherspoon commented
Need to swap test instance over to instance that has MySQL vector support enabled.

2024-03-26 00:32 UTC, totoleon approved these changes

2024-03-26 00:32 UTC, totoleon commented on src/langchain_google_cloud_sql_mysql/vectorstore.py
> +        index_query_options: Optional[QueryOptions] = None,
Better to name it "query_options" instead of index_query_options. In PG QueryOptions is a sub attribute of index, though in Mysql it will be separate. There will be something more than than the index itself such as whether to use KNN query or ANN query, which we call "search_type"

2024-03-26 00:32 UTC, totoleon commented on tests/integration/test_mysql_vectorstore.py
> +import pytest_asyncio
This is not used

2024-03-26 00:32 UTC, totoleon commented on tests/integration/test_mysql_vectorstore_from_methods.py
> +import pytest_asyncio
same this is not used

2024-03-26 04:02 UTC, totoleon commented on tests/integration/test_mysql_vectorstore.py
> +        return get_env_var("DATABASE_ID", "database name on cloud sql instance")
Can we change this to DB_NAME to be consistent with the other tests?

2024-03-26 04:02 UTC, totoleon commented on src/langchain_google_cloud_sql_mysql/__init__.py
>  from .engine import MySQLEngine
Need to include Column here

2024-03-26 04:56 UTC, totoleon requested changes

2024-03-26 04:56 UTC, totoleon commented on tests/integration/test_mysql_vectorstore.py
> +        ids = [str(uuid.uuid4()) for i in range(len(texts))]
nit: "for _ in range"

2024-03-26 04:56 UTC, totoleon commented on tests/integration/test_mysql_vectorstore.py
> +        assert results[0]["mycontent"] == "foo"
This assertion will likely to fail, because the default select order will by the order of the primary key but not the insertion order. If we don't need to guarantee the insertion order, we can remove the assertion.

2024-03-26 05:13 UTC, totoleon commented on tests/integration/test_mysql_vectorstore.py
> +            table_name=DEFAULT_TABLE,
nit: better to add  `overwrite_existing=True,` in fixture setup. So that one failed test won't affect the following ones.

2024-03-26 05:13 UTC, totoleon commented on tests/integration/test_mysql_vectorstore.py
> +    @pytest.fixture(scope="class")
Better to have the table scope="function". Or we should truncate at the beginning of each function as well. Otherwise, if a test fail and doesn't reach the truncate line, it will break the follow tests using the table. Also using per-function table can help parallelize the test later.

With pytest-xdist and per-function, we will be able to do things like `pytest -n 4`

2024-03-26 05:19 UTC, totoleon requested changes

2024-03-26 05:19 UTC, totoleon commented on tests/integration/test_mysql_vectorstore_from_methods.py
> +    async def engine(self, db_project, db_region, db_instance, db_name):
"async " breaks the test.

2024-03-26 05:19 UTC, totoleon commented on tests/integration/test_mysql_vectorstore_from_methods.py
> +        assert results[0]["mycontent"] == "foo"
Same as in the other test, mysql doesn't guarantee the insertion order, and this assertion will be flaky.

2024-03-26 05:21 UTC, totoleon commented on tests/integration/test_mysql_vectorstore.py
> +@pytest.mark.asyncio(scope="class")
No need the async annotation here.

2024-03-26 05:21 UTC, totoleon commented on tests/integration/test_mysql_vectorstore_from_methods.py
> +@pytest.mark.asyncio
No need the async annotation here.

2024-03-26 13:41 UTC, jackwotherspoon commented on tests/integration/test_mysql_vectorstore.py
> +            table_name=DEFAULT_TABLE,
done

2024-03-26 13:41 UTC, jackwotherspoon commented on src/langchain_google_cloud_sql_mysql/vectorstore.py
> +        index_query_options: Optional[QueryOptions] = None,
good idea, done

2024-03-26 13:42 UTC, jackwotherspoon commented on tests/integration/test_mysql_vectorstore.py
> +    @pytest.fixture(scope="class")
done

2024-03-26 17:03 UTC, totoleon approved these changes

2024-03-26 21:08 UTC, averikitsch approved these changes

2024-03-26 21:08 UTC, averikitsch commented on src/langchain_google_cloud_sql_mysql/vectorstore.py
> +        index_query_options: Optional[QueryOptions] = None,
Did we want to update to query_options?

2024-03-26 21:14 UTC, jackwotherspoon commented on src/langchain_google_cloud_sql_mysql/vectorstore.py
> +        index_query_options: Optional[QueryOptions] = None,
it is updated to `query_options`, this comment is pinned on out of date code

2024-03-26 21:19 UTC, jackwotherspoon commented on src/langchain_google_cloud_sql_mysql/engine.py
> +            overwrite_existing (bool): Whether to drop existing table. Default: False.
added

2024-03-26 21:22 UTC, merged