chore: Update renovate.json5
googleapis/langchain-google-cloud-sql-mysql-python pull request #60
Opened 2024-04-05 18:37 UTC by averikitsch

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/langchain-google-cloud-sql-mysql-python/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2024-04-15 17:47 UTC, kurtisvg requested changes

2024-04-15 17:47 UTC, kurtisvg commented on .github/renovate.json5
> +  },
Not following this change. Why do we have a requirements 3-8 and a requirements?

2024-04-15 19:48 UTC, averikitsch commented on .github/renovate.json5
> +  },
I had to cut a separate reqs file for 3.8 since the numpy dep must be pinned to v1.24.4. This change allows for the req file to be recognized and the other dependencies to updated.

2024-04-17 16:22 UTC, kurtisvg approved these changes

2024-04-17 17:05 UTC, merged